import 'dart:convert';

class PhotoMetadata {
  final int? id;            // Optional, will be auto-generated by the database
  final String path;         // Path to the photo file
  final String timestamp;    // Timestamp of when the photo was taken
  final String description;  // Optional description of the photo
  final String location;     // Optional location where the photo was taken

  PhotoMetadata({
    this.id,
    required this.path,
    required this.timestamp,
    this.description = '',
    this.location = '',
  });

  // Convert a PhotoMetadata object into a Map to store it in the database
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'path': path,
      'timestamp': timestamp,
      'description': description,
      'location': location,
    };
  }

  // Create a PhotoMetadata object from a Map (retrieved from the database)
  factory PhotoMetadata.fromMap(Map<String, dynamic> map) {
    return PhotoMetadata(
      id: map['id'],
      path: map['path'],
      timestamp: map['timestamp'],
      description: map['description'],
      location: map['location'],
    );
  }

  // Optional: Convert a PhotoMetadata object into a JSON string for network or file storage
  String toJson() => json.encode(toMap());

  // Optional: Create a PhotoMetadata object from a JSON string
  factory PhotoMetadata.fromJson(String source) => PhotoMetadata.fromMap(json.decode(source));

  @override
  String toString() {
    return 'PhotoMetadata(id: $id, path: $path, timestamp: $timestamp, description: $description, location: $location)';
  }
}
